# Generated by Django 3.2 on 2021-05-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='star',
            field=models.IntegerField(null=True),
        ),
    ]
