# Generated by Django 3.2 on 2021-05-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210525_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Steamed',
            field=models.TextField(null=True),
        ),
    ]
