# Generated by Django 3.2 on 2021-05-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_users_steamed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Steamed',
            new_name='steamed',
        ),
    ]
